export const ADD_CONTENT = 'ADD_CONTENT';
export const GET_CONTENT = 'GET_CONTENT';
export const GET_SINGLE_CONTENT = 'GET_SINGLE_CONTENT';
export const UPDATE_CONTENT = 'UPDATE_CONTENT';
export const ADD_UPDATE_CONTENT = 'ADD_UPDATE_CONTENT'
export const DELETE_CONTENT = 'DELETE_CONTENT';

export const ADD_TO_READING_HISTORY = 'ADD_TO_READING_HISTORY';

export const TOGGLE_TAG = 'TOGGLE_TAG';

export const SORT_BY_FIRST_UPLOAD = 'SORT_BY_FIRST_UPLOAD';
export const SORT_BY_LAST_UPLOAD = 'SORT_BY_LAST_UPLOAD';